### ISSUE TITLE
Not working at all on Manjaro Cinnamon

### ISSUE THREAD

**Issue by jathanasiou** [SrKomodo/shadowfox-updater#10]
The theme has been installed through the [AUR package](https://aur.archlinux.org/packages/shadowfox-updater/) but it doesn't seem to be working at all.

I tried starting with a fresh profile and there was no difference. 

Currently running on
```bash
OS: Manjaro Linux x86_64 
Kernel: 4.14.39-1-MANJARO 
DE: Cinnamon 3.8.2 
Theme: Arc-Maia-Dark [GTK2/3] 
Icons: Vertex-Maia [GTK2/3] 
CPU: AMD Phenom 9550 (4) @ 2.200GHz 
GPU: NVIDIA GeForce GT 720 
Memory: 4234MiB / 7980MiB 
```
So the browser preferences just stick to the 'Default' theme following the GTK3 styling and no pages seems to be affected.

**Comment by SrKomodo** [comment]
Can you elaborate a bit more? What happens when you run the executable? Does it crash? Or does it work but the style changes don't show up on Firefox?

**Comment by jathanasiou** [comment]
Apologies, I had not realized you need to run an executable in order to apply the theme. It seems to be working fine for me.
