### ISSUE TITLE
Defaulting users to Firefox's dark theme

### ISSUE THREAD

**Issue by overdodactyl** [SrKomodo/shadowfox-updater#17]
When using ShadowFox, users need to select the built in dark theme provided by Firefox.

One way to avoid this would be to add the following lines to a `user.js` file that resides in the profile directory:

```js
user_pref("lightweightThemes.selectedThemeID", "firefox-compact-dark@mozilla.org");
user_pref("devtools.theme", "dark");
```
The first line is for the browser theme, the second is for the developer tools. 

In terms of implementation, we would probably need to first check if the file exists.  If so, check whether the lines are already present and either write/don't write them to it.  If not, create the file with the corresponding lines.  

Do you think trying to add this into the updater would be worthwhile or not a good idea/worth the effort?  

`user.js` is often used to harden security/privacy preferences for Firefox (e.x: [ghacks user-js](https://github.com/ghacksuserjs/ghacks-user.js)), so I'm not sure whether or not users would have any concern with a script writing to this file either..

**Comment by SrKomodo** [comment]
It could definitely be done, and doesn't seem very complicated to implement. I guess we could add it as another option on the GUI just like generating the UUIDs.

As soon as i get some spare time ill look into it.

**Comment by overdodactyl** [comment]
Sounds great, thanks!

**Comment by SrKomodo** [comment]
Sorry it took that long, but v1.6.0 hopefully has this implemented

**Comment by overdodactyl** [comment]
No worries at all, thanks for them implementation!

Just tested it out and it seems to work great.

Website should be updated for v1.6.0 as well.
