### ISSUE TITLE
Profile dropdown still rendering after selection

### ISSUE THREAD

**Issue by overdodactyl** [SrKomodo/shadowfox-updater#19]
Parts of the profile dropdown menu are still rendered after making a selection:

![screen shot 2018-09-20 at 11 22 14 am](https://user-images.githubusercontent.com/33071129/45835586-0e25bc00-bcfa-11e8-9f3b-d01f47b05693.png)

The above screenshot is taken after `dev-edition-default` is selected, but several other profile options can still be seen. 

Adjusting the size of the terminal seems to resolve the issue:

![screen shot 2018-09-20 at 11 26 19 am](https://user-images.githubusercontent.com/33071129/45835720-59d86580-bcfa-11e8-815d-5208c0614079.png)

 I'm on macOS 10.14, but this was also reported by a [Linux user on Reddit](https://old.reddit.com/r/ShadowFoxCSS/comments/9ghs79/does_the_dark_scroll_bars_not_work_anymore/e64zkd9/).

Any idea if this is something with the updater or an upstream bug? I quickly glanced through issues on [tview](https://github.com/rivo/tview) but nothing caught my eye

**Comment by SrKomodo** [comment]
Can confirm this is also happening on windows. It appears to be an upstream bug, but I'm not sure so I'm gonna keep the issue open.
