### ISSUE TITLE
Incorrect directory for Linux install

### ISSUE THREAD

**Issue by mwchiao** [SrKomodo/shadowfox-updater#2]
[I don't know if this is the right place to do this]
I am currently on Fedora 27 running Firefox 59.0.2

The current linux_386 release of the updater on the release page gave me an error when I tried to run it. 

I looked into it and found out the line in ui.go (182)
``iniPath = homedir + "/.mozilla/profiles.ini"``

should be
``iniPath = homedir + "/.mozilla/firefox/profiles.ini"``

Building and install worked okay after the change.
I am not completely sure if this directory is the same for all Linux distros but I feel like it's a safe bet.

**Comment by SrKomodo** [comment]
v1.4 should have your fix incorporated. Please tell me if it works now

**Comment by mwchiao** [comment]
![screenshot](https://user-images.githubusercontent.com/23227019/39157100-1e640e3a-470e-11e8-94af-278971f02878.png)
building it myself from the source code works fine. But using chmod on the download on the release page gives me the error in the screenshot. As long as I put in the correct path, it works. However, I would have to type in the path every time I run the updater.

**Comment by SrKomodo** [comment]
Hmm, that is really weird. So the problem shows up when downloaded from github, but not when compiled from source in linux? I would say that it is a cross compilation issue, but travis-ci compiles it on linux machines so it can't be that. I will have to look deeper into this

**Comment by SrKomodo** [comment]
On v1.4.1 the program will no longer ask you for a path, and instead will ask you to move the program to wherever `profiles.ini` is. This removes the issue of having to type the full path each time, but of course it would be a lot more ideal if the program could auto detect this. For the following reasons I'm keeping this issue open until I find an actual solution instead of a workaround

**Comment by mwchiao** [comment]
Both downloading from the release page and building from source are functional for v1.4.1.
It automatically finds the path and there is no need to moving typing in the path or moving the executable.

**Comment by SrKomodo** [comment]
Oh, well I guess the problem somehow fixed itself. Less work for me I guess :P
