### ISSUE TITLE
MacOS make error: xcrun/invalid active developer path

### ISSUE THREAD

**Issue by orvn** [SrKomodo/shadowfox-updater#25]
- [x] xcrun error 

When I `make` the updater or try to install it with `brew install srkomodo/tap/shadowfox-updater`, I get this error:

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

I'm running _MacOS Mojave 10.14.0_.

**Comment by orvn** [comment]
Fixed this by updating _xcode_ command line tools like so:
`xcode-select --install`

(even though I already had the latest _xcode_ installed, I needed to do this)

**Comment by overdodactyl** [comment]
This seems to be a common issue after all Apple's major updates:

https://stackoverflow.com/questions/28706428/invalid-active-developer-path-on-mac-os-x-after-installing-ruby#33012317
