### ISSUE TITLE
No option to unset dark theme

### ISSUE THREAD

**Issue by deathtrip** [SrKomodo/shadowfox-updater#26]
Currently there is no option to unset the dark firefox theme, once it has been set, even by uninstalling shadowfox.
Adding a checkbox to unset it , or unsetting it if the user hasn't selected the dark theme option when updating, would solve the issue.
Also the devtools dark theme could get it's own checkbox, for those that want only one.

**Comment by overdodactyl** [comment]
If you need an immediate fix you can remove the following lines from the `user.js` file that resides in your profile directory:

```js
user_pref("lightweightThemes.selectedThemeID", "firefox-compact-dark@mozilla.org");
user_pref("devtools.theme", "dark");
```
restart your browser, then use the Firefox UI to set the theme you want

**Comment by overdodactyl** [comment]
I'm not sure editing `prefs.js` would work.  

I did the following as a test:

* Create a new profile

* Edit `prefs.js` with dark theme settings

* Open Firefox

* **Result:** Dark themed firefox

* Quit Firefox

* **Result:** Dark theme prefs are erased from `prefs.js`.  Opening Firefox again results in the light theme

**Comment by SrKomodo** [comment]
This issue is insanely old, but i just tested what you did and it doesn't seem to happen anymore. Maybe something changed in a Firefox update? Regardless, im closing this issue.
