### ISSUE TITLE
terminal not executing

### ISSUE THREAD

**Issue by k1nghat** [SrKomodo/shadowfox-updater#28]
im on kubuntu 18.10 and when i download shadowfox_linux_x64 and go to properties it shows it is already set as executable, double clicking on it doesnt bring up the GUI in terminal. if i go to see if the process is running, it is. if i `chmod +x shadowfox_linux_x64` it does the same thing. if i `./shadowfox_linux_x64` from terminal it works fine that way.

im fairly new to linux so i may be making assumptions on how this should work but i have other files that are executable like that that seem to work just fine. also, this has been the issue for me for many versions, i just havent remember to bring an issue. i talked about it here, though: https://www.reddit.com/r/ShadowFoxCSS/comments/9ghs79/does_the_dark_scroll_bars_not_work_anymore/e64zkd9

**Comment by SrKomodo** [comment]
This is expected behaviour, given that double clicking it just runs the program in the background, without actually showing any output. It is necessary to run it from the command line because the UI lives inside the command line
