### ISSUE TITLE
is this for real?

### ISSUE THREAD

**Issue by pleasejust** [SrKomodo/shadowfox-updater#29]
I just wanted the internal fx pages to be in dark mode. A simple cocoa window with checkboxes would suffice. wtf archaic thing is this. Seriously, man. KISS. Keep it simple, stupid. oh right, cross platform. jeez.. anyways, the extracted file (shadowfox_mac_x64) is extensionless. By default it opens in textedit with some garbled text. I don't know what I'm supposed to do with it. Thanks.

**Comment by overdodactyl** [comment]
>I feel like I have to learn css programming.

There's no need to learn any css to install ShadowFox.  

>A simple cocoa window with checkboxes would suffice

This installer provides a cross platform solution with exactly what you are asking for (window with checkboxes).

> Keep it simple, stupid

I command line program with a GUI *is* simple (from the end users perspective)

>the extracted file (shadowfox_mac_x64) is extensionless. By default it opens in textedit with some garbled text. I don't know what I'm supposed to do with it.

Please read the README.md file.

>wtf archaic thing is this..

In the future, please be respectful to the individuals who are contributing to the open-source community and spending their own time creating things others, like yourself, can use.

**Comment by pleasejust** [comment]
I didn't realize I had to type shadowfox in the terminal... sorry, brain fart I guess but the instructions could be clearer.

**Comment by overdodactyl** [comment]
From the readme:

>On MacOS, you can install using Homebrew via `brew install srkomodo/tap/shadowfox-updater` and then running the program with `shadowfox`

**Comment by pleasejust** [comment]
yes, I got that... it didn't click in my head initially that running meant typing it in terminal. I'm not used to that. I own a mac afterrall. Anyways, it worked. It's unbelievable. You're a genius. No flickering when I open fx for the first time either. Thanks.

**Comment by pleasejust** [comment]
Also, do you have any idea about how other issues like when I use .tabbrowser-tab:not([pinned]) {max-width: 325px !important;} the tabs get buggy when I close and reopen new ones. I have a high rez display and need wider tabs, can't find any solution to this anywhere. Thanks again.

**Comment by SrKomodo** [comment]
I'm just going to close this issue, given that the issues discussed in here at this point belong to the main shadowfox repository and not the shadowfox-updater repo
