### ISSUE TITLE
Layout - Full path not visible

### ISSUE THREAD

**Issue by stonecrusher** [SrKomodo/shadowfox-updater#3]
I didn't change window size so either it is windows standard or defined by the updater.

![screenshot 4](https://user-images.githubusercontent.com/1388389/39180768-0b086a5c-47b8-11e8-8341-b6d219068f47.png)

You could get rid of the padding on the left and insert a newline after `Profile to use:`, though.

This should hopefully be enough. Otherwise word-wrap is needed.

shadowfox_windows_amd64.exe V1.40

**Comment by SrKomodo** [comment]
Now on v1.4.1 the profile list only shows the name instead of the full path
![image](https://user-images.githubusercontent.com/22225222/39218261-2468f3f8-47fa-11e8-9847-c1d5cd91aea8.png)
This should hopefully make the program more friendly, and fix your issue

**Comment by stonecrusher** [comment]
Jep, that's also good to go! Thanks!
