### ISSUE TITLE
Firefox 65 

### ISSUE THREAD

**Issue by GTK66** [SrKomodo/shadowfox-updater#31]
Windows Color has to be changed or an adjust must be made for ShadowFox to work properly. Thiis problem did not exist with Firefox 64 . This is in Windows 10 The checkmark has to be left blank which ruins Win 10 colors or a dark color has to be chosen.

[img]https://i.imgur.com/GuZWQ7i.png[/img]

**Comment by overdodactyl** [comment]
@GTK66 - is this related to the updater or the theming of Firefox?  If the later please close this issue and open up one here:

https://github.com/overdodactyl/ShadowFox/issues

Either way, we likely need more details about what's going on; I'm not entirely sure what you mean by "adjust must be made for ShadowFox to work properly," or what the problem you are observing is.  

Screenshots and as much detail as possible is always helpful.

Thanks!

**Comment by GTK66** [comment]
I installed a Black Theme by Madonna that took care of this issue but others are having it.


[img]https://i.imgur.com/JEmDX8X.png[/img<https://i.imgur.com/JEmDX8X.png%5b/img>]

[img]https://i.imgur.com/C3z2kqF.png[/img<https://i.imgur.com/C3z2kqF.png%5b/img>]


[img]https://i.imgur.com/v4krYiZ.png[/img<https://i.imgur.com/v4krYiZ.png%5b/img>]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GTK66** [comment]
This issue is fixed for me but it still will affect other users. Firefox 65 was changed .
