### ISSUE TITLE
Mac: Dies because it cannot find non-existent files

### ISSUE THREAD

**Issue by neha-sri** [SrKomodo/shadowfox-updater#34]
Reporting for due diligence. It does work if I manually copy both `userContent.css` and `userChrome.css` over. 

PS: This is on a workplace computer which is behind bazillion proxies so its possible its just my proxy settings. But the error message could be cleaner instead of panic. Also it can provide links and instructions to manually download the files. Not high priority

```
> ./shadowfox_mac_x64 -set-dark-theme
userChrome.css Couldn't be downloaded: Get https://raw.githubusercontent.com/overdodactyl/ShadowFox/master/userChrome.css: dial tcp 151.101.20.133:443: i/o timeout
You should probably report this crash in https://github.com/SrKomodo/shadowfox-updater/issues/new
Press enter to close the program

panic: Get https://raw.githubusercontent.com/overdodactyl/ShadowFox/master/userChrome.css: dial tcp 151.101.20.133:443: i/o timeout

goroutine 1 [running]:
main.checkErr(0x137c8b9, 0x25, 0x13c38e0, 0xc000188180)
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/profiles.go:17 +0x1ce
main.cli()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/cli.go:33 +0x2be
main.main()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:11 +0x2c
```

**Comment by SrKomodo** [comment]
Yup, this is a network error. I will add some instructions to manually download the files if it crashes

**Comment by AmbrosiaDevelopments** [comment]
Did you add the instructions? I still cannot do this and cannot configure a proxy during the process.

**Comment by escape0707** [comment]
> Yup, this is a network error. I will add some instructions to manually download the files if it crashes

Bump. Would like to try as your instructions but still can't find it.
And `proxychains` seems can't be used as a way to proxy the `shadowfox-updater`.
And where should I manually download those two css files?
