### ISSUE TITLE
CSS getting overwritten - Is this supposed to happen?

### ISSUE THREAD

**Issue by bobf32** [SrKomodo/shadowfox-updater#35]
Hi,

1. Run shadowfox updater
2. Select FF profile from dropdown
3. Select Install/update shadowfox

A chrome folder is created under my profile, with two files, userChrome.css (94 Kb) and userContent.css (127 Kb).

4. Start Firefox

userChrome.css reduces to 1 Kb, new file created in chrome folder, WBbackupuserChrome.css 94Kb.

5. Open any bookmarked page in FF.

Page opens after blank, white page appears briefly. 

It's the temporary whiteness I'm trying to get rid of, and the reason for trying shadowfox. Would I be right in saying something is awry?

**Comment by SrKomodo** [comment]
something seems to be very awry indeed, these strange modifications to the files are not being made by shadowfox, but another program. What version of Firefox are you using? And are there any special modifications you did to it?

**Comment by bobf32** [comment]
D'oh. Window blinds. My bad.
