### ISSUE TITLE
Sources for userChrome.css generation

### ISSUE THREAD

**Issue by anonymous133** [SrKomodo/shadowfox-updater#36]
Hi and thank you for this updater!

I have a question. I'd like to style firefox using pywal/wpg. I have to put an import into color_variables.css for that but I can't find the source file anywhere the updater uses to create the files in my firefox profile folder.

Could you please tell me how I can do that?

Thank you very much!

@import url('file:///home/account/.config/wpg/formats/colors.css');

**Comment by SrKomodo** [comment]
The file you are looking for is probably `<profile>/chrome/ShadowFox_customization/colorOverrides.css`. For example, my current one looks like this:
```
--tone-1: hsl(214, 40%, 98%) !important;
--tone-2: hsl(214, 40%, 94%) !important;
--tone-3: hsl(214, 22%, 85%) !important;
--tone-4: hsl(214, 22%, 70%) !important;
--tone-5: hsl(223, 12%, 45%) !important;
--tone-6: hsl(223, 12%, 30%) !important;
--tone-7: hsl(221, 15%, 23%) !important;
--tone-8: hsl(227, 14%, 17%) !important;
--tone-9: hsl(221, 15%, 22%) !important;
```
Remember that after changing the file, you must run the updater again to apply the changes.
