### ISSUE TITLE
unnecessary darker text (low contrast)

### ISSUE THREAD

**Issue by Mahdi321** [SrKomodo/shadowfox-updater#37]
You have made the common mistake that most dark theme creators, do. The mistake that in addition to swapping text and background color (which is good and necessary), has done an unnecessary additional step and has made text color darker
It reduces contrast and actually put more pressure on the eye

**Comment by SrKomodo** [comment]
This repository is for the updater, not the actual css. You might want to create a new issue on the [original repo](https://github.com/overdodactyl/ShadowFox/issues/new)
