### ISSUE TITLE
Error installing via Homebrew

### ISSUE THREAD

**Issue by tjahjono** [SrKomodo/shadowfox-updater#38]
When I attempt to install via homebrew, I get the following: `Authentication failed for https://github.com/srkmodo/homebrew-tap/`.

**Comment by SrKomodo** [comment]
It seems you have mistyped my username as `srkmodo` instead of `srkomodo`, run this command to install it properly: `brew install srkomodo/tap/shadowfox-updater`
After that just run `shadowfox` to open the updater.

**Comment by tjahjono** [comment]
🤦‍♂ 

Thank you
