### ISSUE TITLE
Updater version check possible?

### ISSUE THREAD

**Issue by NomDeMorte** [SrKomodo/shadowfox-updater#39]
Edit: I am a doofus and used an old version with a bug that has been fixed. Could the updater do a version check/self-update?

> 
> TL;DR Don't delete stuff that doesn't need to be, please!
> Rename/move it if you must, but don't delete!
> 
> So, I was having trouble with my CSS and I wasn't sure if my own customization userChrome was interfering with shadowfox (This has happened before and turned out to be a SF bug)... So I used the uninstaller, so I could start from vanilla FF.... and it not only removed the shadowfox CSS files, but deleted the entire ShadowFox_Customization directory.... WHICH HAD ALL MY BACKUPS IN IT. (Yes, I'm a good boy and have a backup from earlier, on another drive, so I only lost a few days work, but still....)
> 
> Uninstalling ShadowFox does not imply deleting user-created files... I think that routine could do with some attention. It's entirely possible I've missed something but, I don't see any need to touch that directory at all. Just remove (or better yet, rename!) the userChrome and userContent CSS that was created by the installer in the first place should be enough, no?  
> 
> Thanks man I love your work but this was a SERIOUS bummer. I'm just glad that the uninstaller didn't delete the .backup files it created when I had updated while testing, so I still have some remnants of my old work.

**Comment by NomDeMorte** [comment]
I thought I'd try and be helpful and see if I could find the offending code and it looks like you already fixed it and I have an old version of the installer

https://github.com/SrKomodo/shadowfox-updater/commit/57a71c88b64c131648b60b2bd4ff649dd803f953

Shoot me. Feel free to close this if it's fixed and I'm a doofus. Sorry!

**Comment by arguablykomodo** [comment]
v2.2.0 now checks for updates and notifies you if there is a new version available.

**Comment by NomDeMorte** [comment]
Awesome work man thanks!
