### ISSUE TITLE
Updater has trouble finding profile

### ISSUE THREAD

**Issue by NomDeMorte** [SrKomodo/shadowfox-updater#40]
I think this is best described with images.
I start the updater, and see this:
![image](https://user-images.githubusercontent.com/45681208/57966309-6305f900-7993-11e9-9570-d2fbe56a1508.png)
I press Enter, and I see this:
![image](https://user-images.githubusercontent.com/45681208/57966318-829d2180-7993-11e9-8651-2d5cf6ae5700.png)
Note: This profile listed is not my default profile - older versions of the updater selected that profile
I press Enter again and I get this:
![image](https://user-images.githubusercontent.com/45681208/57966330-b415ed00-7993-11e9-906c-81575d212dca.png)
Now, it has selected my primary profile. Pressing Enter one more time, selects it.

I can also use the cursor keys in that menu. When I do, the default profile becomes visible, and the empty row below the other profile, disappears.

Edit: I can work around this by placing the updater in the directory with the profiles.ini as suggested in README.MD, however the reason I mention this is that obviously, whatever the updater is doing when I press enter that second time, contains the 'fix' for this - rather than having to specifically locate the updater.

**Comment by SrKomodo** [comment]
The new UI on v2.0.0 no longer has this issue
