### ISSUE TITLE
Newer versions of updater do not take backups when updating

### ISSUE THREAD

**Issue by NomDeMorte** [SrKomodo/shadowfox-updater#41]
I recently updated to a new version of this updater ( related: https://github.com/SrKomodo/shadowfox-updater/issues/39 )

Today, I made a mistake and went to restore from the .backup file... And there isn't one. Was the feature to make backups, removed? Perhaps this is related to the installer not finding my profile? https://github.com/SrKomodo/shadowfox-updater/issues/40 I moved the installer adjacent to the profiles.ini and it did not make backups again, so I don't think that's the issue.

**Comment by SrKomodo** [comment]
Fixed in v2.0.0, it was just a dumb typo on the code :P

**Comment by NomDeMorte** [comment]
Mate, that new version is super slick.

I spent 4 hours yesterday searching for a bug and it was a missing semi-colon. We've ALL been there LOL
