### ISSUE TITLE
Running without having zenity installed results in an error

### ISSUE THREAD

**Issue by Remedan** [SrKomodo/shadowfox-updater#43]
Currently it is possible to use the updater in either GUI or CLI mode. The GUI mode requires zenity being installed.

The CLI mode functions perfectly fine without zenity. But if I run shadowfox-updater _without any flags_ and without having zenity installed, it stops with the following error:

```
panic: dlgs: exec: "zenity": executable file not found in $PATH; exec: "qarma": executable file not found in $PATH

goroutine 1 [running]:
main.checkErr(0x0, 0x0, 0x7611a0, 0xc000012d20)
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:10 +0xf2
main.createUI()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:18 +0xeb
main.main()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:11 +0x38
```

I suggest that if I run the updater without any flags and without zenity a helpful message should be printed instead.

**Comment by SrKomodo** [comment]
I re-added the fallback ui, now if you don't have zenity installed a text-only prompt should replace it.
