### ISSUE TITLE
There is no method of seeing the installer's version information

### ISSUE THREAD

**Issue by crkellen** [SrKomodo/shadowfox-updater#45]
The version information of the installer is neither baked into the .exe (so you could see it when right-clicking -> properties), nor is it anywhere (that I can find) within the running application.

Having some way of reading the version information would be very useful.

**Comment by NomDeMorte** [comment]
Related: https://github.com/SrKomodo/shadowfox-updater/issues/39

**Comment by SrKomodo** [comment]
v2.1.0 now (hopefully) shows the current version number on the application dialogs.
