### ISSUE TITLE
FF 68 about:addons extension details - unable to read text

### ISSUE THREAD

**Issue by seanob86** [SrKomodo/shadowfox-updater#47]
Just upgraded to FF 68 and noticed extension details text is hidden with shadowfox 2.2.0.
I have tried uninstalling from my FF profile and then installing again but text is still not readable.

The only way to read the extension details text is to either.
1. Uninstall shadowfox from FF profile
2. With shadowfox installed, highlight the text under the details section of the extension to reveal the text

<img width="692" alt="Screen Shot 2019-07-09 at 22 47 55" src="https://user-images.githubusercontent.com/45988261/60893764-0c10f780-a251-11e9-9d66-9e87fb130477.png">

<img width="680" alt="Screen Shot 2019-07-09 at 22 47 13" src="https://user-images.githubusercontent.com/45988261/60893770-0e735180-a251-11e9-84f3-fa509ee60729.png">

<img width="529" alt="Screen Shot 2019-07-09 at 22 56 37" src="https://user-images.githubusercontent.com/45988261/60893997-66aa5380-a251-11e9-967c-8f3dfdfaeb5a.png">

**Comment by TemperTrap29187** [comment]
Yep, same here.

**Comment by 3k2** [comment]
![image](https://user-images.githubusercontent.com/11908261/61182904-a2269280-a642-11e9-9c29-180be236c776.png)

![image](https://user-images.githubusercontent.com/11908261/61182909-ad79be00-a642-11e9-9e34-653f0ca7d47c.png)

indeed same issue here. I tried to reinstall and nothing.. seems the new firefox changed something?

**Comment by arguablykomodo** [comment]
Sorry for the late reply. This issue isn't really about the updater, but rather with shadowfox itself. I would recommend you move it to https://github.com/overdodactyl/ShadowFox
