### ISSUE TITLE
(feature request): Can move the addressbar to the bottom

### ISSUE THREAD

**Issue by aemonge** [SrKomodo/shadowfox-updater#48]
Can we make a default CSS to apply always, to enable addressbar in the bottom of the UI such as suggested here https://support.mozilla.org/en-US/questions/1248277?page=2 ?

**Comment by arguablykomodo** [comment]
If you go to `about:profiles`, click "Open Directory" on the profile in use, then go to `chrome/ShadowFox_customization`, there should be a file called `userChrome_customization.css`, inside that file you can paste any customizations you want, such as the one you just posted, and then after running the updater again the changes should be applied
