### ISSUE TITLE
 universial theme installer and plugins not show right with it

### ISSUE THREAD

**Issue by tsunami2311** [SrKomodo/shadowfox-updater#64]
I went to use the install all looked fine but it mess with ublock pop up button  color and it tabs which i dont not like is there way to keep that from happen?

**Comment by tsunami2311** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/12301593/101393076-843f7a80-3894-11eb-8361-2546c5ab9d2a.png)
![Screenshot (16)](https://user-images.githubusercontent.com/12301593/101393077-84d81100-3894-11eb-80f8-58394d752612.png)
![Screenshot (17)](https://user-images.githubusercontent.com/12301593/101393079-84d81100-3894-11eb-9aa2-ab8cb74d1c0c.png)
![Screenshot (18)](https://user-images.githubusercontent.com/12301593/101393080-84d81100-3894-11eb-9f96-96cc79b4bcc6.png)
![Screenshot (19)](https://user-images.githubusercontent.com/12301593/101393081-8570a780-3894-11eb-85a5-92e2c584c95b.png)
![Screenshot (20)](https://user-images.githubusercontent.com/12301593/101393082-8570a780-3894-11eb-94cc-2130679871d1.png)
![Screenshot (21)](https://user-images.githubusercontent.com/12301593/101393083-8570a780-3894-11eb-91e1-3c5dd5384f62.png)


I have ublock origin advanced setting set too
uiFlavor classic
uiStyles font-family: sans-serif

as i dont like the new gui style nor the text cause text on my system it  blurry and as such uncomfortable to  read

**Comment by tsunami2311** [comment]
Effect cookie auto delete to
![Screenshot (23)](https://user-images.githubusercontent.com/12301593/101393460-23647200-3895-11eb-9352-aefed3ae7adc.png)
![Screenshot (24)](https://user-images.githubusercontent.com/12301593/101393462-23647200-3895-11eb-8ba1-a1ec7c5f4412.png)
![Screenshot (22)](https://user-images.githubusercontent.com/12301593/101393463-23fd0880-3895-11eb-8fed-cfcd49bd5c7f.png)


Is there verison of auto updater that just leave plugin alone and just make  firefox stuff dark?
I normal use https://github.com/overdodactyl/ShadowFox which done manually but dont seem to reallly be update much if at all anymore

**Comment by swinkapepa** [comment]
Is anyone know how to fix this issue??

**Comment by tsunami2311** [comment]
this has been abandoned this project from what i can tell.

I been redirected to 
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme

But i stops using them I just userchrome.css with 4 lines to make Proton UI look the way I want seeing I was only using this for dark theme to be applied to the browser it self I dont care for orwant addons to be dark, but the above should fix it
