### ISSUE TITLE
uBlock Origin dark theme issues after installing shadowfox for windowsx64

### ISSUE THREAD

**Issue by garteful** [SrKomodo/shadowfox-updater#67]
Hi

I've installed shadowfox_windows_x64 from [here](https://github.com/arguablykomodo/shadowfox-updater), on Firefox on Windows 10 machine.
Settings:
Default profile
Auto-Generate UUIDs: Yes
Set Firefox dark theme: No (already have the FF dark theme).

My extensions became dark, except to uBlock Origin extension which is 75% dark, and when I click on "more" the fonts are white on white (Please see image).

Any suggestions to fix this issue ?

Thanks in advance 

g

![image](https://user-images.githubusercontent.com/92165976/136581057-7e09fbb9-1ccc-4e8e-a916-115d59ff5f70.png)

**Comment by DrWhoCares** [comment]
See #68.
