### ISSUE TITLE
shadowfox-updater fails to run

### ISSUE THREAD

**Issue by osleg** [SrKomodo/shadowfox-updater#7]
It fails in `termite` terminal. Works fine in urxvt tho
Setting $TERM to xterm fixes the issue but it shouldn't happen in the first place
```
$ ./shadowfox_linux_amd64 
panic: terminal entry not found

goroutine 1 [running]:
main.createUI()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:177 +0x2de7
main.main()
	/home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:4 +0x20
```
This happens for both version from AUR and downloaded from release.
tested with versions:
1.4.0
1.4.1

**Comment by SrKomodo** [comment]
Sadly the UI library I use for the program doesn't appear to work on `termite`. You will have to use xterm or any other terminal that works.

[Related issue from the library](https://github.com/rivo/tview/issues/2)

**Comment by SrKomodo** [comment]
Just so you know @osleg , now in 1.5.0 the program has a fallback text-only UI that will run if the cool UI doesnt work properly, so you should be able to use `termite` for it
