### ISSUE TITLE
Support for snap installation of firefox

### ISSUE THREAD

**Issue by qazip** [SrKomodo/shadowfox-updater#8]
Would it be too hard to add support for firefox installed via snap?

**Comment by SrKomodo** [comment]
If you want shadowfox-updater to work with non default installations, all you have to do is move it to where your `profiles.ini` file is located. Here are the instructions to do so:
1. Go to `about:profiles` on Firefox and click "Open Folder" on the "Root Directory" row
2. Now go one folder up, you should be able to see the `profiles.ini` file
3. move the shadowfox-updater executable into that folder

**Comment by qazip** [comment]
Oh, nice. Sorry, that is probably in the README.

Thank you!
