### ISSUE TITLE
Backup files naming schema

### ISSUE THREAD

**Issue by CaptaPraelium** [SrKomodo/shadowfox-updater#9]
See here: https://github.com/overdodactyl/ShadowFox/issues/147
When the script runs it creates a backup of the existing css files and renames them. However, they retain the .css extension, which is causing them to be loaded by the userchrome.js extension.

Might I suggest that the files be renamed with an alternative extension? Perhaps something like
userChrome.backup.2018-03-08_10-05-27.css
Could instead be
userChrome.css.2018-03-08_10-05-27.bk

By the way, LOVE this script! Great work man :)

**Comment by SrKomodo** [comment]
That is strange, because the program already backs up using the .backup extension instead of .css (for example this is how a backup i just made looks like: `userChrome.css.2018-05-15-17-38-48.backup`)

Are you running the latest version? What OS are you using?

**Comment by overdodactyl** [comment]
@CaptaPraelium, is it possible the backups that you are referring to, and the ones causing problems, were generated with the old Windows updater?

**Comment by SrKomodo** [comment]
@CaptaPraelium Any updates on this?

**Comment by overdodactyl** [comment]
I've added a fork of the userChrome.js gist here:

https://gist.github.com/overdodactyl/c0c3698b7b9a635f3bf8c0ac9fcd3442

This version should only load files within the directory `chrome/userjs_files`, which is probably advisable for ShadowFox users anyways to prevent duplicate loading of the customization files.

**Comment by CaptaPraelium** [comment]
Yep, I'm stupid. It was the old script. The file date was a dead giveaway. Sorry to have wasted your time guys :(
